### PR TITLE
stopped <stateless/> components being built

### PR DESCRIPTION
**Pull request by The-Code-Monkey**
stopped code from building <stateless /> & <stateful /> components that did nothing.

### CODE REVIEW

**Comment by menothe** [comment]
Hi, this PR seems to be removing all stateless components in the app, but this contradicts what we're doing. We'd like to give users the ability to nest stateless components in other stateful or stateless components. Can you please explain in greater detail what you are trying to fix?

**Comment by The-Code-Monkey** [comment]
what this does is that it stops it from writing <stateless /> as this does nothing it doesnt stop normal components from rendering just he random components that do nothing

**Comment by The-Code-Monkey** [comment]
do this 

app
    home
       hero
          img
          title
    about
       hero

see what happens when you run it normally compared to what mine does

**Comment by menothe** [comment]
In your example, can you be more specific with which components are stateful/stateless and what the nesting should look like (parent-child relationships)?
Thank you

**Pull request merged**
